# Module 6 Exercises - Correlation and Models

### Exercise 1:

From the datasets folder, load the "tamiami.csv" file as a dataframe. Rename the columns (in order) to the following:

- location
- sales
- employees
- restaurants
- foodcarts
- price

Then do a correlation table on that dataframe. What features (columns) are correlated? What features aren't correlated?

In [1]:
import pandas as pd
import numpy as np

In [2]:
Location = "datasets/tamiami.csv"
df = pd.read_csv(Location)

df.head()

,Cart Location,Hot Dog Sales,Employees in Nearby Office Buildings,Num of Nearby Restaurants,Num of Other Food Carts Nearby,Price
0,1,100,1600,8,12,4.16
1,2,80,1200,6,13,4.63
2,3,450,2800,19,6,0.50
3,4,580,4300,19,2,0.47
4,5,100,1400,6,13,4.24

In [12]:
df.rename(columns={'Cart Location':'location', 'Hot Dog Sales':'sales', 'Employees in Nearby Office Buildings':'employees', 'Num of Nearby Restaurants': 'restaurants', 'Num of Other Food Carts Nearby':'foodcarts'}, inplace=True)
df.head()

   location  sales  employees  restaurants  foodcarts  Price
0         1    100       1600            8         12   4.16
1         2     80       1200            6         13   4.63
2         3    450       2800           19          6   0.50
3         4    580       4300           19          2   0.47
4         5    100       1400            6         13   4.24

In [13]:
#creates a table of correlation values  #MIRACLE VALUE !!!!!
#NO COORINATION AT ALL [VALUE = 0]
df.corr()

             location     sales  employees  restaurants  foodcarts     Price
location     1.000000  0.042705  -0.068923     0.049701   0.077219 -0.138444
sales        0.042705  1.000000   0.943238     0.913674  -0.919762 -0.966378
employees   -0.068923  0.943238   1.000000     0.856976  -0.874692 -0.881540
restaurants  0.049701  0.913674   0.856976     1.000000  -0.761793 -0.933951
foodcarts    0.077219 -0.919762  -0.874692    -0.761793   1.000000  0.860154
Price       -0.138444 -0.966378  -0.881540    -0.933951   0.860154  1.000000

What features (columns) are correlated? What features aren't correlated?

In [ ]:
#All of them seem to have a strong positive and negative coorination. if you have question ask Kanisha!

### Exercise 2:

Using the dataframe from the previous exercise, choose features (columns) to create a linear regression formula to predict sales. Try it with and without the y-intercept. How does it make a difference? Does adding or removing features in your model formula make a difference in the output?

In [14]:
#use this library to build a statistical test for linear regression
import statsmodels.formula.api as smf

In [15]:
result = smf.ols('sales ~ location + Price + foodcarts', data=df).fit()

In [16]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.965
Model:                            OLS   Adj. R-squared:                  0.961
Method:                 Least Squares   F-statistic:                     237.0
Date:                Sat, 13 Apr 2019   Prob (F-statistic):           5.39e-19
Time:                        10:13:21   Log-Likelihood:                -147.02
No. Observations:                  30   AIC:                             302.0
Df Residuals:                      26   BIC:                             307.7
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    581.1520     18.859     30.816      0.000     542.388     619.916
location      -0.5833      0.808     -0.722      0.477      -2.243       1.077
Price        -75.7789      8.584     -8.828      0.000     -93.423     -58.135
foodcarts    -12.7023      3.128     -4.061      0.000     -19.132      -6.273
==============================================================================
Omnibus:                        0.003   Durbin-Watson:                   2.146
Prob(Omnibus):                  0.999   Jarque-Bera (JB):                0.158
Skew:                          -0.015   Prob(JB):                        0.924
Kurtosis:                       2.645   Cond. No.                         59.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [17]:
result = smf.ols('sales ~ location + Price + foodcarts-1', data=df).fit()

In [18]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.593
Model:                            OLS   Adj. R-squared:                  0.548
Method:                 Least Squares   F-statistic:                     13.13
Date:                Sat, 13 Apr 2019   Prob (F-statistic):           1.78e-05
Time:                        10:16:15   Log-Likelihood:                -201.40
No. Observations:                  30   AIC:                             408.8
Df Residuals:                      27   BIC:                             413.0
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
location      11.5117      4.242      2.714      0.011       2.807      20.216
Price        -86.1379     51.559     -1.671      0.106    -191.928      19.652
foodcarts     23.3037     17.441      1.336      0.193     -12.483      59.090
==============================================================================
Omnibus:                        3.998   Durbin-Watson:                   0.795
Prob(Omnibus):                  0.135   Jarque-Bera (JB):                3.416
Skew:                           0.820   Prob(JB):                        0.181
Kurtosis:                       2.785   Cond. No.                         28.4
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""